version: "4.37.2"
services: 
  api:
    image: linedward/fastapi
    depends_on:
      - postgres
    ports:
      - 80:8000
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - AUTH_ALGORITHM=${AUTH_ALGORITHM}
      - ACCESS_TOKEN_EXPIRY_MINS=${ACCESS_TOKEN_EXPIRY_MINS}

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: