name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: fastAPI
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password123
      AUTH_SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      AUTH_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRY_MINS: 30
    runs-on: ubuntu-latest
    steps:
      - name: pull git repo
        uses: actions/checkout@v4
      - name: install python version 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: run pytest
        run: |
          pip install pytest
          pytest